### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by premkumarsepuri** [tusharjindal353/PathfinderApp#1]
not installed pods

**Comment by tusharjindal353** [comment]
you can install pods bhai first running a "pod init" command from terminal in your project directory and then you can add pod to this podfile.and after that you run pod install

**Comment by premkumarsepuri** [comment]
i already installed pods. But still im getting expection. Kindly look into your project one

**Comment by tusharjindal353** [comment]
it is working in my pc as well as my students pc.can you send me the screenshots of the error so that i can help u further
